### PR TITLE
Squeeze array when exporting tiffs

### PR DESCRIPTION
**Pull request by noisysky**
I don't know if it's useful or the best way to do this, but works for now

### CODE REVIEW

**Comment by AlanMWatson** [comment]
Iana,

I think if you instantiate the IMS class with option 'squeeze_output=True', this will solve your problem without having to put in these if statements for specific use cases.

**Comment by noisysky** [comment]
Yes, you are right. However it might be useful to force squeeze output within these methods. Like this:

```
def method_to_extract_tiffs(self, ...):
    backup = self.squeeze_output
    self.squeeze_output = True
    <original code in the method>
    self.squeeze_output = backup
```

**Comment by noisysky** [comment]
Because in these methods it should always be True. The same instance of ims class might be used both for Napari and for extracting tiffs. Also people are forgetful (especially me) and won't always remember to type squeeze_output=True. :-)

**Comment by AlanMWatson** [comment]
Should we just default the reader to squeeze_output = True and change the Napari reader to always instantiate the ims class with squeeze_output = False?

**Comment by AlanMWatson** [comment]
Resolved this by making 'squeeze_output=True' as default when opening ims class

**Comment by AlanMWatson** [comment]
Lol.  Off==False.

Let's chat a little later.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Watson, Alan M
Sent: Tuesday, March 29, 2022 2:24:46 PM
To: CBI-PITT/imaris_ims_file_reader ***@***.***>; CBI-PITT/imaris_ims_file_reader ***@***.***>
Cc: Review requested ***@***.***>
Subject: RE: [CBI-PITT/imaris_ims_file_reader] Squeeze array when exporting tiffs (PR #8)


Should we just default the reader to squeeze_output = True and change the Napari reader to always instantiate the ims class with squeeze_output = False?

**Pull request closed without merging**
